### ISSUE TITLE
pkgdown `development: auto` setting has broken PR documentation previews on dev version of package

### ISSUE THREAD

**Issue by annakrystalli** [hubverse-org/hubverse-developer-actions#4]
Since updating packages to the new release process, including dev versions of documentations via the `development: auto` pkgdown setting, documentation previews of dev versions of packages has been broken.
e.g. https://66fa7d43ab61c232fc2c3fd2--hubvalidations-pr-previews.netlify.app/

<img width="481" alt="image" src="https://github.com/user-attachments/assets/42a9ad31-8d83-4bcb-8405-13facd442796">

When building docs for a development version of a package, the docs build in `.docs/dev`. The netlify preview however lanches the site in `.docs/`. I _think_ what's happening is that it's not finding an index page in there and returning a netlify page not found error.

This needs to be fixed in `pkgdown-netlify-preview/pkgdown-netlify-preview.yaml` and/or netlify setting to somehow add `/dev` to the preview URL when publishing previews of development versions of packages

**Comment by annakrystalli** [comment]
These might be useful:
- https://docs.netlify.com/configure-builds/overview/#set-the-publish-directory
- https://docs.netlify.com/configure-builds/file-based-configuration/

**Comment by zkamvar** [comment]
> When building docs for a development version of a package, the docs build in `.docs/dev`. The netlify preview however lanches the site in `.docs/`. I _think_ what's happening is that it's not finding an index page in there and returning a netlify page not found error.

I believe this is correct.

it appears if you add `/dev` to the preview URL, it will show up: https://66fa7d43ab61c232fc2c3fd2--hubvalidations-pr-previews.netlify.app/dev/

**Comment by zkamvar** [comment]
We could add a step that checks the version number in the description and creates the path based on that:

```yaml
      - id: deploy-dir 
        run: |
          if [[ $(grep -c -E 'sion. ([0-9]*\.){3}' ${{ github.workspace }}/DESCRIPTION) == 1 ]]; then
            echo 'dir=./docs/dev' >> $GITHUB_OUTPUT
          else
            echo 'dir=./docs' >> $GITHUB_OUTPUT
      - name: Deploy PR preview to Netlify
        if: contains(env.isPush, 'false')
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: '${{ steps.deploy-dir.outputs.dir }}'
```
